### ISSUE TITLE
CI incompability

### ISSUE THREAD

**Issue by ad-m** [wurosh/cake#3]
Hello,

I use `Makefile` to keep my CI script portable. See about that idea in  https://www.freecodecamp.org/news/a-lightweight-tool-agnostic-ci-cd-flow-with-github-actions/. So far I was using docker-compose in Makefile to keep environment portable. Effectily I have flow: `ci configuration -> Makefile -> docker-compose -> build tools`. I am to merge `Makefile` and `docker-compose` by replace it by cake.

Unfortunatly, cake is not CI compatible:

```
cake: info: using docker
cake: info: running 'make update'
cake: info: in container 'cake-foi-watch-2366390509'
cake: info: using Dockerfile '/home/runner/work/foi-watch/foi-watch/Dockerfile'
cake: info: in directory '/home/runner/work/foi-watch/foi-watch'
the input device is not a TTY
```

What we can do about that? Any suggestion?

Kind regards,
`docker-compose` enable TTY (opt-out) only if TTY is available.

**Comment by cyruseuros** [comment]
That said, I tend not to use cake in CI, it just emulates my CI environment. Since those systems typically provision images for you, I tend to just run `make` naked.
